
services:
  - name: client
    type: web
    rootDir: client
    buildCommand: npm install
    startCommand: npm run dev
  - name: server
    type: web
    rootDir: server
    buildCommand: npm install
    startCommand: node server
